# Generated by Django 2.2.23 on 2021-06-16 04:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('T', 'Transgendered'), ('U', 'Unknown'), ('O', 'Others')], max_length=1, null=True)),
                ('birthDate', models.DateField(verbose_name='date of birth')),
                ('deceasedDate', models.DateField(blank=True, null=True, verbose_name='deceased date')),
                ('maritalStatus', models.CharField(blank=True, choices=[('A', 'Annulled'), ('D', 'Divorced'), ('I', 'Interlocutary'), ('L', 'Legally Separated'), ('M', 'Married|'), ('P', 'Polygamous'), ('N', 'Never Married'), ('O', 'Domestic Partner'), ('U', 'Unmarried'), ('W', 'Widowed'), ('U', 'Unknown')], max_length=1, null=True, verbose_name='marital status')),
                ('ethnicity', models.CharField(blank=True, choices=[('ML', 'Malay'), ('CH', 'Chinese'), ('IN', 'Indian'), ('IB', 'Iban'), ('KM', 'Kadazan Murut'), ('IM', 'West Malaysia indigenous'), ('IS', 'Other East Malaysia indigenous'), ('EA', 'East Asian'), ('HI', 'Hispanic'), ('PI', 'Pacific Islander'), ('AR', 'Arab'), ('PE', 'Persian'), ('UN', 'Unspecified')], max_length=2, null=True)),
                ('religion', models.CharField(blank=True, choices=[('IS', 'Islam'), ('BD', 'Buddhist'), ('TA', 'Taoist'), ('CH', 'Christian'), ('HI', 'Hindu'), ('AG', 'Agnostic')], max_length=2, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100, verbose_name='full name')),
                ('family', models.CharField(blank=True, max_length=60, null=True, verbose_name='family or last name')),
                ('given', models.CharField(blank=True, max_length=60, null=True, verbose_name='given or first name')),
                ('middle', models.CharField(blank=True, max_length=60, null=True, verbose_name='middle name')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='salutations or honorifics')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('use', models.CharField(choices=[('US', 'usual'), ('OF', 'official'), ('TM', 'temporary'), ('NN', 'nickname'), ('AN', 'anonymous'), ('OL', 'old'), ('MA', 'maiden')], max_length=2)),
                ('active', models.BooleanField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idValue', models.CharField(max_length=30)),
                ('idType', models.CharField(choices=[('NR', 'National registration id'), ('PP', 'Passport id'), ('MC', 'Medicaid card'), ('HR', 'Hospital registration number')], max_length=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'phone'), ('fax', 'fax'), ('email', 'E-mail'), ('url', 'url'), ('sms', 'sms')], max_length=5)),
                ('value', models.CharField(max_length=255)),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('B', 'billing')], max_length=1)),
                ('rank', models.PositiveSmallIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactpoints', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_contacts', to='subjects.Organization')),
                ('patient', models.ManyToManyField(related_name='patient_contacts', to='patients.Patient')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_contacts', to='subjects.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
                ('preferred', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('B', 'billing')], max_length=1)),
                ('type', models.CharField(choices=[('PO', 'postal'), ('PH', 'physical'), ('BO', 'both')], max_length=2)),
                ('text', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('postalCode', models.CharField(max_length=5, verbose_name='post code')),
                ('country', models.CharField(default='MY', max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='patients.Patient')),
            ],
        ),
    ]
